### ISSUE TITLE
QQ clears default yank buffer when transitioning from response to request

### ISSUE THREAD

**Issue by ianks** [nicwest/QQ.vim#17]
I am attempting to yank something from my response. I `y`ank it, then open a new request by running `QQ`. When I am in the new request, I now cannot `p`aste what I yanked from the previous response buffer. Is this default behavior/cam I stop QQ from doing this?

Thanks in advance! QQ has proved to be invaluable so far.

**Comment by nicwest** [comment]
it's something that I have also noticed, I believe it's due to clearing the last line when buffers are repopulated:

https://github.com/nicwest/QQ.vim/search?utf8=%E2%9C%93&q=Gddgg

`Gddgg` should be `G"_ddgg`

**Comment by nicwest** [comment]
hopefully that should fix it, let me know if you are still seeing it, or you find anything else.

**Comment by nicwest** [comment]
This looks likes it's fixed going to close
