### ISSUE TITLE
Config for turning off SSL Cert Verification

### ISSUE THREAD

**Issue by sunnypp** [nicwest/QQ.vim#23]
I am using Postman for testing API calls to a local VM machine.  I am switching to use (neo)Vim and found this plugin yet I always receive "No response", though the sample call in README.md does give me a response (in HTML though).

Incidentally I also switched from Chrome App Postman to Native App Postman (on macOS).  Suddenly Postman also gave me "No Response" and I saw the suggestion about turning off SSL Certificate Verification there.  I turned it off and I got back the API response from my VM.

I'd like to know if that is possible with QQ.vim?

**Comment by nicwest** [comment]
if you pull the latest version, and add the following to your request it should (hopefully) do what you want

```
OPTION: :insecure: true
```

**Comment by sunnypp** [comment]
Thank you very much!  This is really a very quick feature implementation ;)
